export enum Colors {
    RED = "red",
    PURPLE = "purple",
    BLACK = "black",
    BLUE = "blue",
    LIGHT_BLUE = "lightblue",
    DARK_BLUE = "darkblue",
    LIGHT_GREEN = "lightgreen",
    GREEN = "green",
    DARK_GREEN = "darkgreen",
    GRAY = "gray",
    SILVER = "silver",
    YELLOW = "yellow",
    GOLD = "gold",
    ORANGE = "orange",
    PINK = "pink",
    BROWN = "brown",
    WHITE = "white",
  }